### ISSUE TITLE
Error in the output of Mario.c

### ISSUE THREAD

**Issue by deshmukhmayur** [dietms/Mario-VARADSP#1]
As given in the PSet, the program needs to take input from the user, and then print the desired output in the given format.
For eg. If the user inputs 5, the program print:
        ##
      ###
    ####
  #####
######

Your output is perfect in shape, just notice the first row of the output and the number of rows.

**Comment by VARADSP** [comment]
Issue Solved

**Comment by deshmukhmayur** [comment]
Good but not quite there yet.
Try changing the initial value of i in the first for loop to 1.
`for (i=1;...`
